name = "GregTech-TimeEcho"
author = "nvaz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc0b6eb6c1e612a802bd281e5b9f90cfe8f580ed6110ab64217ca7d9c2af7e78"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
