name = "GregTech-TimeEcho"
author = "nvaz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10d20f7962da7faa880b3a832a2bcf219ff233f0e9fba3f830f224799b625348"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
