name = "GregTech-TimeEcho"
author = "nvaz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1a4d5b3f0746d4d3474a823210fa4f24157e47ce023bbe10b3f0bb6f3d2e05"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
